
services:

  ca:
    build:
      context: .
      dockerfile: ca/Dockerfile
    networks:
      - insecure-net
    volumes:
      - ./logs:/data  # Share `logs` folder with host
    cap_add:
      - NET_ADMIN
      - NET_RAW



  alice:
    depends_on:
      - ca
    build:
      context: .
      dockerfile: alice/Dockerfile
    networks:
      - insecure-net

  bob:
    depends_on:
      - alice
    build:
      context: .
      dockerfile: bob/Dockerfile
    networks:
      - insecure-net


networks:
  insecure-net:
    driver: bridge
