version: '3.8'
services:
  alice:
    build:
      context: .
      dockerfile: alice/Dockerfile
    networks:
      - insecure-net

  bob:
    build:
      context: .
      dockerfile: bob/Dockerfile
    networks:
      - insecure-net

  eve:
    build:
      context: .
      dockerfile: eve/Dockerfile
    networks:
      - insecure-net
    volumes:
      - ./logs:/data  # Share `logs` folder with host
    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  insecure-net:
    driver: bridge
